# we use an extended json format with #-marked comments
[ # for every word, try each of these components until an analysis has been produced

  ###############
  # dict lookup #
  ###############
  # for the 'dict' method, we expect a JSON dict in the style of ../dict/vocab.json 

  # voab_full lookup (to be curated!)
  { "method": "dict", 
    "components": [ "dict/vocab_full.json" ]
  },

  # lemmatizer v.0.2 vocab (to be dropped, or replaced by expanded dict)
  { "method": "dict",
  	"components": [ "dict/vocab.json" ] 
  } ,

  ###############
  # fst parsing #
  ###############
  # for the 'fst' method, we expect compiled SFST transducers (*.a)
  # the components form a chain of transducers executed *on the shell* with fst-parse

  # normalize + vocab_full lookup
  { "method": "fst",
  	"components": [ "x2norm.a", "norm_dict_full.a" ] 
  },

  # normalize + infl + lexeme lookup
  { "method": "fst",
  	"components": [ "x2norm.a", "infl_dict.a" ] 
  },

  # normalize + infl + word_formation
  { "method": "fst", "components": [ "x2norm.a", "inflection.a", "word_formation_0.a" ] },
  { "method": "fst", "components": [ "x2norm.a", "inflection.a", "word_formation_1.a" ] }, 
  { "method": "fst", "components": [ "x2norm.a", "inflection.a", "word_formation_2.a" ] }

  # we could also add s High German parser



 ]